# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/index.html for details

version: 2

# Set the OS, Python version and build tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Python package installation
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Formats to build
formats:
  - pdf
  - htmlzip