seed: 43
dry_run: false
validate_only: false
eos:
  type: metamodel_cse
  ndat_metamodel: 100
  nmax_nsat: 25.0
  nb_CSE: 8
  crust_name: DH
tov:
  type: anisotropy
  min_nsat_TOV: 0.75
  ndat_TOV: 100
  nb_masses: 100
prior:
  specification_file: prior.prior
likelihoods:
- type: constraints_eos
  enabled: true
- type: radio
  enabled: true
  pulsars:
  - name: J1614
    mass_mean: 1.94
    mass_std: 0.06
  - name: J0740
    mass_mean: 2.08
    mass_std: 0.14
- type: nicer
  enabled: true
  pulsars:
  - name: J0030
    amsterdam_model_dir: ../../../../jesterTOV/inference/flows/models/nicer_maf/J00300451/amsterdam_st_pst
    maryland_model_dir: ../../../../jesterTOV/inference/flows/models/nicer_maf/J00300451/maryland_2spot_rm
  N_masses_evaluation: 20
  N_masses_batch_size: 20
sampler:
  type: smc-rw
  n_particles: 5000
  n_mcmc_steps: 10
  target_ess: 0.9
  random_walk_sigma: 0.05
  n_eos_samples: 5000
  output_dir: ./outdir/
postprocessing:
  enabled: true
  make_cornerplot: true
  make_massradius: true
  make_pressuredensity: true
