seed: 43
dry_run: false
validate_only: false
eos:
  type: metamodel_cse
  ndat_metamodel: 100
  nmax_nsat: 25.0
  nb_CSE: 8
  crust_name: DH
tov:
  min_nsat_TOV: 0.75
  ndat_TOV: 100
  nb_masses: 100
  tov_solver: gr
prior:
  specification_file: prior.prior
likelihoods:
- type: constraints_eos
  enabled: true
- type: gw
  enabled: true
  events:
  - name: GW170817
  penalty_value: -99999.0
  N_masses_evaluation: 2000
  N_masses_batch_size: 1000
  seed: 42
sampler:
  type: flowmc
  n_chains: 1000
  n_loop_training: 30
  n_loop_production: 30
  n_local_steps: 100
  n_global_steps: 100
  n_epochs: 30
  learning_rate: 0.001
  output_dir: ./outdir/
postprocessing:
  enabled: true
  make_cornerplot: false
  make_massradius: true
  make_pressuredensity: true
