"""End-to-end tests for SMC Random Walk sampler.

SMC-RW is the production-ready, recommended sampler.
These tests verify the full pipeline: config -> sampler.sample() -> SamplerOutput.
"""

import copy

import pytest
import jax
import jax.numpy as jnp
import numpy as np

from jesterTOV.inference.config.schema import InferenceConfig
from jesterTOV.inference.run_inference import (
    setup_prior,
    setup_transform,
    setup_likelihood,
    determine_keep_names,
)
from jesterTOV.inference.samplers import create_sampler

from .conftest import validate_sampler_output, NEP_PARAMS


@pytest.mark.slow
@pytest.mark.integration
@pytest.mark.e2e
class TestSMCRandomWalkE2E:
    """End-to-end tests for SMC-RW sampler."""

    def test_smc_rw_prior_only_full_pipeline(self, smc_rw_prior_config, e2e_temp_dir):
        """Test full SMC-RW pipeline with prior-only likelihood (cheapest test).

        This exercises:
        - Config loading and validation
        - Prior setup
        - Transform setup (MetaModel)
        - Likelihood setup (zero + constraints_eos)
        - Sampler creation via factory
        - Full sampling run
        - SamplerOutput generation
        """
        # Create config from dict
        config = InferenceConfig(**smc_rw_prior_config)

        # Setup components (following run_inference.py flow)
        prior, _fixed_params = setup_prior(config)
        keep_names = determine_keep_names(config, prior)
        transform = setup_transform(config, prior=prior, keep_names=keep_names)
        likelihood = setup_likelihood(config, transform)

        # Create sampler via factory
        sampler = create_sampler(
            config=config.sampler,
            prior=prior,
            likelihood=likelihood,
            likelihood_transforms=[transform],
            seed=config.seed,
        )

        # Run sampling
        key = jax.random.PRNGKey(config.seed)
        sampler.sample(key)

        # Get output via standardized interface
        output = sampler.get_sampler_output()

        # Validate output structure
        validate_sampler_output(output, expected_params=NEP_PARAMS, min_samples=50)

        # SMC-specific: check weights in metadata
        assert "weights" in output.metadata, "SMC output missing weights"

        # Validate weights sum to ~1 (normalized)
        weights = output.metadata["weights"]
        assert jnp.isclose(
            jnp.sum(weights), 1.0, atol=0.01
        ), f"Weights don't sum to 1: {jnp.sum(weights)}"

    def test_smc_rw_chieft_full_pipeline(self, smc_rw_chieft_config, e2e_temp_dir):
        """Test full SMC-RW pipeline with chiEFT likelihood.

        This exercises the realistic use case with:
        - MetaModel+CSE transform
        - chiEFT likelihood (integrates EOS against constraint bands)
        - EOS constraint checking
        """
        config = InferenceConfig(**smc_rw_chieft_config)

        prior, _fixed_params = setup_prior(config)
        keep_names = determine_keep_names(config, prior)
        transform = setup_transform(config, prior=prior, keep_names=keep_names)
        likelihood = setup_likelihood(config, transform)

        sampler = create_sampler(
            config=config.sampler,
            prior=prior,
            likelihood=likelihood,
            likelihood_transforms=[transform],
            seed=config.seed,
        )

        key = jax.random.PRNGKey(config.seed)
        sampler.sample(key)

        output = sampler.get_sampler_output()

        # For CSE, we have NEP params + nbreak + CSE grid params
        # The CSE grid params are auto-generated by prior parser
        assert "K_sat" in output.samples
        assert "nbreak" in output.samples

        # Should have finite samples in valid ranges
        for param, arr in output.samples.items():
            assert jnp.isfinite(arr).all(), f"Parameter {param} has non-finite values"

    def test_smc_rw_produces_valid_posterior(self, smc_rw_prior_config, e2e_temp_dir):
        """Test that SMC-RW produces samples in prior bounds."""
        config = InferenceConfig(**smc_rw_prior_config)

        prior, _fixed_params = setup_prior(config)
        keep_names = determine_keep_names(config, prior)
        transform = setup_transform(config, prior=prior, keep_names=keep_names)
        likelihood = setup_likelihood(config, transform)

        sampler = create_sampler(
            config=config.sampler,
            prior=prior,
            likelihood=likelihood,
            likelihood_transforms=[transform],
            seed=config.seed,
        )

        key = jax.random.PRNGKey(config.seed)
        sampler.sample(key)

        output = sampler.get_sampler_output()

        # Check samples are within prior bounds
        # K_sat: [150, 300]
        assert jnp.all(output.samples["K_sat"] >= 150.0)
        assert jnp.all(output.samples["K_sat"] <= 300.0)

        # L_sym: [10, 200]
        assert jnp.all(output.samples["L_sym"] >= 10.0)
        assert jnp.all(output.samples["L_sym"] <= 200.0)

    def test_smc_rw_deterministic_with_seed(self, smc_rw_prior_config, e2e_temp_dir):
        """Test that SMC-RW is deterministic given same seed."""
        config = InferenceConfig(**smc_rw_prior_config)

        # Run twice with same seed
        results = []
        for _ in range(2):
            prior, _fixed_params = setup_prior(config)
            keep_names = determine_keep_names(config, prior)
            transform = setup_transform(config, prior=prior, keep_names=keep_names)
            likelihood = setup_likelihood(config, transform)

            sampler = create_sampler(
                config=config.sampler,
                prior=prior,
                likelihood=likelihood,
                likelihood_transforms=[transform],
                seed=config.seed,
            )

            key = jax.random.PRNGKey(config.seed)
            sampler.sample(key)
            results.append(sampler.get_sampler_output())

        # Compare first sample of K_sat
        assert jnp.allclose(
            results[0].samples["K_sat"][:10],
            results[1].samples["K_sat"][:10],
            atol=1e-6,
        ), "SMC-RW not deterministic with same seed"

    def test_smc_rw_adaptive_step_size_beats_mistuned_fixed_sigma(
        self,
        smc_rw_mistuned_fixed_sigma_config,
        smc_rw_adaptive_step_size_config,
        e2e_temp_dir,
    ):
        """Adaptive step size should recover from a deliberately too-large starting sigma.

        Cross-checks against an expected outcome (not just a smoke test): with
        random_walk_sigma set too large, the fixed-sigma sampler's acceptance rate should
        collapse well below the 0.234 target, while the adaptive sampler -- started from the
        exact same mis-tuned sigma -- should self-correct (via pretuning + per-step
        Robbins-Monro adaptation) to a mean acceptance rate much closer to target.
        """

        def run(config_dict):
            config = InferenceConfig(**config_dict)
            prior, _fixed_params = setup_prior(config)
            keep_names = determine_keep_names(config, prior)
            transform = setup_transform(config, prior=prior, keep_names=keep_names)
            likelihood = setup_likelihood(config, transform)
            sampler = create_sampler(
                config=config.sampler,
                prior=prior,
                likelihood=likelihood,
                likelihood_transforms=[transform],
                seed=config.seed,
            )
            sampler.sample(jax.random.PRNGKey(config.seed))
            return sampler.metadata["mean_acceptance"]

        fixed_acceptance = run(smc_rw_mistuned_fixed_sigma_config)
        adaptive_acceptance = run(smc_rw_adaptive_step_size_config)

        target = 0.234
        fixed_error = abs(fixed_acceptance - target)
        adaptive_error = abs(adaptive_acceptance - target)

        assert adaptive_error < fixed_error, (
            f"Adaptive step size did not improve on mis-tuned fixed sigma: "
            f"fixed acceptance={fixed_acceptance:.4f} (|error|={fixed_error:.4f}), "
            f"adaptive acceptance={adaptive_acceptance:.4f} (|error|={adaptive_error:.4f})"
        )


@pytest.mark.slow
@pytest.mark.integration
@pytest.mark.e2e
class TestSMCRandomWalkFinalRejuvenation:
    """Tests for the optional final-rejuvenation move
    (``n_final_rejuvenation_steps``, see ``smc/rejuvenation.py``).

    BlackJAX's tempered SMC builds each step's MCMC move to target the
    *previous* step's distribution, so the terminal resample-to-uniform-
    weights step (done to produce an i.i.d.-looking sample for storage)
    leaves some exact-duplicate particles behind (SMC resampling
    degeneracy at ESS < n_particles) that are never subsequently moved.
    ``n_final_rejuvenation_steps`` > 0 runs a few extra MCMC steps
    targeting the fixed final posterior after that resample, which should
    eliminate the duplicates without shifting the posterior.
    """

    @staticmethod
    def _run(config_dict, n_final_rejuvenation_steps, seed):
        config_dict = copy.deepcopy(config_dict)
        config_dict["sampler"][
            "n_final_rejuvenation_steps"
        ] = n_final_rejuvenation_steps
        config_dict["seed"] = seed
        config = InferenceConfig(**config_dict)
        prior, _fixed_params = setup_prior(config)
        keep_names = determine_keep_names(config, prior)
        transform = setup_transform(config, prior=prior, keep_names=keep_names)
        likelihood = setup_likelihood(config, transform)
        sampler = create_sampler(
            config=config.sampler,
            prior=prior,
            likelihood=likelihood,
            likelihood_transforms=[transform],
            seed=config.seed,
        )
        sampler.sample(jax.random.PRNGKey(config.seed))
        return sampler.get_sampler_output()

    def test_rejuvenation_eliminates_exact_duplicates_without_shifting_posterior(
        self, smc_rw_prior_config
    ):
        """Same seed for both runs: the annealing schedule and the
        terminal resample are bitwise identical between the two, so any
        difference is caused purely by the extra rejuvenation MCMC steps
        (an invariance-preserving move on the *same* fixed final target,
        not an independent re-run) -- isolating the effect cleanly.
        """
        seed = 123
        out_off = self._run(smc_rw_prior_config, 0, seed)
        out_on = self._run(smc_rw_prior_config, 30, seed)

        samples_off = np.column_stack(
            [np.asarray(out_off.samples[k]) for k in NEP_PARAMS]
        )
        samples_on = np.column_stack(
            [np.asarray(out_on.samples[k]) for k in NEP_PARAMS]
        )
        n_particles = samples_off.shape[0]
        n_unique_off = len(np.unique(samples_off, axis=0))
        n_unique_on = len(np.unique(samples_on, axis=0))

        assert n_unique_off < n_particles, (
            "Expected the baseline (no rejuvenation) run to contain some "
            "exact-duplicate particles from SMC resampling degeneracy -- "
            "if this now fails, either this lightweight config's "
            "n_particles is too small to reliably reproduce the artifact, "
            "or something upstream changed (e.g. target_ess, resampling)."
        )
        assert n_unique_on == n_particles, (
            f"Rejuvenation should eliminate exact-duplicate particles: "
            f"got {n_unique_on}/{n_particles} unique (baseline had "
            f"{n_unique_off}/{n_particles})"
        )

        # Bias check: rejuvenation only adds invariance-preserving MCMC
        # steps targeting the same fixed final posterior the pre-
        # rejuvenation particles already (approximately) represent, so
        # per-parameter means should barely move -- generous tolerance
        # since this is a smoke check on a tiny (n_particles=100) run, not
        # a precision benchmark.
        mean_off = samples_off.mean(axis=0)
        mean_on = samples_on.mean(axis=0)
        std_off = samples_off.std(axis=0)
        standard_error = std_off / np.sqrt(n_particles)
        assert np.all(np.abs(mean_on - mean_off) < 5 * standard_error), (
            f"Posterior means shifted more than expected after adding "
            f"rejuvenation: max |shift|/SE = "
            f"{np.max(np.abs(mean_on - mean_off) / standard_error):.2f}"
        )
