seed: 43
dry_run: false
validate_only: false
transform:
  type: metamodel_cse
  ndat_metamodel: 100
  nmax_nsat: 25.0
  nb_CSE: 8
  min_nsat_TOV: 0.75
  ndat_TOV: 100
  nb_masses: 100
  crust_name: DH
prior:
  specification_file: prior.prior
likelihoods:
- type: constraints_eos
  enabled: true
- type: zero
  enabled: true
sampler:
  type: smc-rw
  n_particles: 2000
  n_mcmc_steps: 10
  target_ess: 0.9
  random_walk_sigma: 0.1
  output_dir: ./outdir/
postprocessing:
  enabled: true
  make_cornerplot: false
  make_massradius: true
  make_pressuredensity: true
data_paths: {}
