seed: 44
dry_run: false
validate_only: false
eos:
  type: metamodel_cse
  ndat_metamodel: 100
  nmax_nsat: 25.0
  nb_CSE: 8
  crust_name: DH
tov:
  min_nsat_TOV: 0.75
  ndat_TOV: 100
  nb_masses: 100
  tov_solver: gr
prior:
  specification_file: prior.prior
likelihoods:
- type: constraints_eos
  enabled: true
  penalty_causality: -1.0e10
  penalty_stability: -1.0e5
  penalty_pressure: -1.0e5
- type: chieft
  enabled: true
  low_filename: ../../../../jesterTOV/inference/data/chiEFT/2402.04172/low.dat
  high_filename: ../../../../jesterTOV/inference/data/chiEFT/2402.04172/high.dat
  nb_n: 100
sampler:
  type: flowmc
  n_chains: 1000
  n_loop_training: 30
  n_loop_production: 20
  n_local_steps: 100
  n_global_steps: 100
  n_epochs: 30
  learning_rate: 0.001
  output_dir: ./outdir/
postprocessing:
  enabled: true
  make_cornerplot: false
  make_massradius: true
  make_pressuredensity: true
