seed: 43
dry_run: false
validate_only: false
transform:
  type: metamodel_cse
  ndat_metamodel: 100
  nmax_nsat: 25.0
  nb_CSE: 8
  min_nsat_TOV: 0.75
  ndat_TOV: 100
  nb_masses: 100
  crust_name: DH
prior:
  specification_file: prior.prior
likelihoods:
- type: constraints_eos
  enabled: true
- type: zero
  enabled: true
sampler:
  type: flowmc
  n_chains: 1000
  n_loop_training: 10
  n_loop_production: 10
  n_local_steps: 100
  n_global_steps: 100
  n_epochs: 20
  learning_rate: 0.001
  output_dir: ./outdir/
data_paths: {}
