seed: 45
dry_run: false
validate_only: false
transform:
  type: metamodel_cse
  ndat_metamodel: 100
  nmax_nsat: 25.0
  nb_CSE: 8
  min_nsat_TOV: 0.75
  ndat_TOV: 100
  nb_masses: 100
  crust_name: DH
prior:
  specification_file: prior.prior
likelihoods:
- type: constraints_eos
  enabled: true
- type: nicer
  enabled: true
  pulsars:
  - name: J0740
    amsterdam_samples_file: ../../../../jesterTOV/inference/data/NICER/J07406620_amsterdam_gamma_NICERXMM_equal_weights_recent.npz
    maryland_samples_file: ../../../../jesterTOV/inference/data/NICER/J07406620_maryland_unknown_NICERXMM_RM.npz
  N_masses_evaluation: 20
  N_masses_batch_size: 10
sampler:
  type: blackjax-ns-aw
  n_live: 1400
  n_delete_frac: 0.5
  n_target: 60
  max_mcmc: 5000
  max_proposals: 1000
  termination_dlogz: 0.1
  n_eos_samples: 10000
  output_dir: ./outdir/
postprocessing:
  enabled: true
  make_cornerplot: false
  make_massradius: true
  make_pressuredensity: true
