seed: 45
dry_run: false
validate_only: false
eos:
  type: metamodel_cse
  ndat_metamodel: 100
  nmax_nsat: 25.0
  nb_CSE: 8
  crust_name: DH
tov:
  min_nsat_TOV: 0.75
  ndat_TOV: 100
  nb_masses: 100
  type: gr
prior:
  specification_file: prior.prior
likelihoods:
- type: constraints_eos
  enabled: true
- type: nicer
  enabled: true
  pulsars:
  - name: J0740
    amsterdam_model_dir: ../../../../jesterTOV/inference/flows/models/nicer_maf/J07406620/amsterdam_gamma_nicerxmm
    maryland_model_dir: ../../../../jesterTOV/inference/flows/models/nicer_maf/J07406620/maryland_unknown_nicerxmm_rm
  N_masses_evaluation: 20
  N_masses_batch_size: 10
sampler:
  type: blackjax-ns-aw
  n_live: 1400
  n_delete_frac: 0.5
  n_target: 60
  max_mcmc: 5000
  max_proposals: 1000
  termination_dlogz: 0.1
  n_eos_samples: 10000
  output_dir: ./outdir/
postprocessing:
  enabled: true
  make_cornerplot: false
  make_massradius: true
  make_pressuredensity: true
