seed: 42
dry_run: false
validate_only: false
eos:
  type: spectral
  crust_name: SLy
  n_points_high: 100
tov:
  ndat_TOV: 100
  nb_masses: 100
  min_nsat_TOV: 0.75
  type: gr
prior:
  specification_file: prior.prior
likelihoods:
- type: constraints_eos
  enabled: true
- type: constraints_gamma
  enabled: true
  penalty_gamma: -1.0e10
- type: radio # an arbitrary low MTOV cutoff likelihood
  enabled: true
  pulsars:
  - name: J0000
    mass_mean: 1.0
    mass_std: 0.1
  nb_masses: 100
sampler:
  type: smc-rw
  n_particles: 1000
  n_mcmc_steps: 10
  target_ess: 0.9
  random_walk_sigma: 0.05
  n_eos_samples: 1000
  output_dir: ./outdir/
postprocessing:
  enabled: true
  make_cornerplot: true
  make_massradius: true
  make_pressuredensity: true
